// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqHNKP2P2pe2-CQlqDo3Y9JKcqPYikGU',
    appId: '1:396980749319:web:05d2681c4f5fe808fcd6a2',
    messagingSenderId: '396980749319',
    projectId: 'instagram-clone-77d71',
    authDomain: 'instagram-clone-77d71.firebaseapp.com',
    storageBucket: 'instagram-clone-77d71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmHti16_A8qRhyy9mBbzAsl-DrQX-z-IQ',
    appId: '1:396980749319:android:335f8c3a37d58d8cfcd6a2',
    messagingSenderId: '396980749319',
    projectId: 'instagram-clone-77d71',
    storageBucket: 'instagram-clone-77d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1k1Ecl4t8xqZJZpcBaHVAokwh0L6ltA',
    appId: '1:396980749319:ios:d83ef36509e816f7fcd6a2',
    messagingSenderId: '396980749319',
    projectId: 'instagram-clone-77d71',
    storageBucket: 'instagram-clone-77d71.appspot.com',
    iosClientId: '396980749319-9kk21hudv0aonbtp4lb7uvj57f3e5a94.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1k1Ecl4t8xqZJZpcBaHVAokwh0L6ltA',
    appId: '1:396980749319:ios:d83ef36509e816f7fcd6a2',
    messagingSenderId: '396980749319',
    projectId: 'instagram-clone-77d71',
    storageBucket: 'instagram-clone-77d71.appspot.com',
    iosClientId: '396980749319-9kk21hudv0aonbtp4lb7uvj57f3e5a94.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );
}
